---
- name: "Install php and related packages"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "php-common"
      - "php-cli"
      - "php-json"
      - "php-readline"
      - "php-mbstring"
      - "php-gd"
      - "php-intl"
      - "php-curl"
      - "php-ldap"
      - "php-xsl"
      - "libapache2-mod-php"
      - "gettext"

- name: "Look up PHP version"
  shell: php -v | grep -Po '(?<=PHP\s)\d\.\d'
  register: php_version

- name: Install local.ini
  template:
    src: local.ini
    dest: "/etc/php/{{ php_version.stdout }}/local.ini"

- name: Create symbolic links to local.ini
  file:
    src:  "/etc/php/{{ php_version.stdout }}/local.ini"
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/conf.d/local.ini"
    state: link
  with_items:
    - apache2
    - cli
...
