---
- name: Install php and related packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php-common
    - php-cli
    - php-json
    - php-readline
    - php-mysql
    - php-mcrypt
    - php-mbstring
    - php-gd
    - php-intl
    - php-curl
    - php-ldap
    - php-xsl
    - libapache2-mod-php
    - gettext

- name: Install local.ini
  template:
    src: local.ini.j2
    dest: /etc/php/7.0/local.ini

- name: Create symbolic links to local.ini
  file:
    src:  /etc/php/7.0/local.ini
    dest: /etc/php/7.0/{{ item }}/conf.d/local.ini
    state: link
  with_items:
    - apache2
    - cli

- name: Copy composer installer
  copy:
    src: install_composer.sh
    dest: /usr/local/bin/install_composer
    mode: 0755

- name: Install Composer
  command: /usr/local/bin/install_composer
  args:
    creates: /usr/local/bin/composer

- name: Configure Github Oauth Token for Composer
  become: no
  command: composer config -g github-oauth.github.com {{ github_oauth_token }}
  args:
    creates: '~/.config/composer/auth.json'
  # If github pulls are slow or stall, be sure to set this!!!
  when: vault_github_oauth_token is defined

- name: Install PHPUnit
  get_url:
    url: https://phar.phpunit.de/phpunit.phar
    dest: /usr/local/bin/phpunit
    mode: 0755
...
