; We always want to know when the slightest thing goes wrong
; in a PHP script
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
html_errors = Off

; Many of our applications are geography based.
; This sets our location information, as the default, for all PHP applications.
date.timezone = {{ linux_ntp.timezone }}
date.default_latitude  = 39.169927
date.default_longitude = -86.536806
intl.default_locale = en_US

; Ubuntu does not use sensible INI settings for PHP sessions
session.use_strict_mode = 1
session.gc_probability  = 1
session.cookie_httponly = 1
session.cookie_secure   = 1

; This stub is here to quickly turn XDebug on and off during development
;xdebug.profiler_enable = 1
pcre.jit = 0
